### PR TITLE
Support latest GHC (and latest stackage nightly)

### PR DESCRIPTION
**Pull request by psibi**
This PR should be properly reviewed as I have only made sure that it
compiles fine and the test suites are passed.

Summary of the changes:
* Only support latest 4 major GHC's. With xmonad also doing the same,
I made the same decision here.
* In recent version of network (>= 3.0), the connectTo function isn't
present. So, safeConnect function has been changed accordingly. (This
is the part that need review from the person actually using the library).

Related to: https://github.com/xmonad/xmonad-extras/issues/24

### CODE REVIEW

**Comment by joachifm** [comment]
Thank you

**Comment by psibi** [comment]
@joachifm Can a new hackage release be made ?

**Comment by joachifm** [comment]
@psibi sure. Unfortunately I currently have no time for this project; if you care to, a release is basically: pick fixes to libmpd-0.9 branch, bump version, tag it, upload new archive to Hackage.

**Comment by psibi** [comment]
@joachifm Yes, I could do that. But I don't think I have access to upload it to Hackage.

**Comment by joachifm** [comment]
@psibi I could add  you to the maintainer group, if you have a Hackage user account.

**Comment by psibi** [comment]
@joachifm My hackage account name is psibi: https://hackage.haskell.org/user/psibi

**Comment by joachifm** [comment]
@psibi added

**Comment by psibi** [comment]
@joachifm Thanks, I will do a release this weekend.

**Comment by joachifm** [comment]
Sounds good. Thank you

**Pull request merged**
