### PR TITLE
breaking: Async support

### PR DESCRIPTION
**Pull request by matthewleon**
This adds a number of dependencies, but it's the most conservative way I could find to simply support running commands async.

It probably needs some tests, but I figured I'd submit this for review to make sure this path makes sense to you, first.

### CODE REVIEW

**Comment by joachifm** [comment]
I'm unsure about the utility of using `TVars` for individual state components but if this solves your use case I'm happy to take it, doesn't seem too disruptive & can be iterated upon.

**Comment by matthewleon** [comment]
Regarding the `TVar`s in `ReaderT`, three things.

(I'm somewhat new to this style of async programming in Haskell, so please correct me if I'm making a mistake here. I'd prefer to get this as right as possible.)

1) This prevents race conditions when running two asynchronous `MPDMonad` operations, at least one of which can modify state. There are several points in the code that come immediately to mind as potential edge cases, perhaps most obviously setting a password.

2) More pragmatically, even ignoring the above, I'm not sure how to share `StateT` between async threads of execution without some complex machinery that will use `MVars`, at a minimum. Whatever we set up to `wait` for `idleAsync` can be on its own, separate, thread, living within `MonadMPD`, and may make state-modifying operations like, say, `close`.

3) Even more pragmatically, the `StM` type (https://hackage.haskell.org/package/monad-control-1.0.2.2/docs/Control-Monad-Trans-Control.html#t:StM) for a combination of `ErrorT` and `StateT` would make the user-facing API for operations like `idleAsync` pretty gross, I think.

Thoughts?

**Comment by joachifm** [comment]
It depends on whether you want to support threads to deal with shared state & control the connection. In that case I suppose it makes sense to do it this way. I had a more limited version in mind, where you permit async to the point of letting `idle` fire without blocking but not support changing passwords, closing the connections & whatnot.

In any case, I'm fine seeing how this works out.

**Comment by matthewleon** [comment]
> I had a more limited version in mind, where you permit async to the point of letting idle fire without blocking but not support changing passwords, closing the connections & whatnot.

To compare possibilities, I'm going to try, on another branch, making a version that does this. It might end up being friendlier to the end user. I think in this case `idleAsync` would take a callback within `IO`, and that might work to insulate the end user from the unpleasantness of `StM`.

**Comment by matthewleon** [comment]
I'm still not satisfied with my approach here. Will try some experiments and return to this.

**Comment by joachifm** [comment]
@matthewleon I've sent you an invite to be a collaborator, as I'm not really actively working on improving this anymore. Still happy to look at PRs, of course.

**Comment by matthewleon** [comment]
@joachifm Thanks. I'll appreciate having my ideas and code reviewed before any merging.

**Comment by matthewleon** [comment]
I'm reworking the approach from this branch and will come back to this problem with something better soon.

**Pull request closed without merging**
